//search bar
let careers = [
    "Accountant",
    "Actor",
    "Aerospace Engineer",
    "Architect",
    "Biomedical Scientist",
    "Baker",
    "Business Analyst",
    "Chef",
    "Civil Engineer",
    "Copywriter",
    "Data Scientist",
    "Dentist",
    "Digital Marketing Specialist",
    "Electrical Engineer",
    "Environmental Engineer",
    "Environmental Scientist",
    "Event Planner",
    "Fashion Designer",
    "Financial Analyst",
    "Fitness Trainer",
    "Genetic Counselor",
    "Geologist",
    "Graphic Designer",
    "Historian",
    "Horticulturist",
    "Human Resources Manager",
    "Illustrator",
    "Information Security Analyst",
    "Interior Designer",
    "Java Developer",
    "Journalist",
    "Judge",
    "Kindergarten Teacher",
    "Kinesiologist",
    "Kitchen Designer",
    "Landscape Architect",
    "Librarian",
    "Linguist",
    "Marketing Manager",
    "Medical Technologist",
    "Mechanical Engineer",
    "Nurse Practitioner",
    "Network Administrator",
    "Nutritionist",
    "Optometrist",
    "Occupational Therapist",
    "Operations Manager",
    "Pharmacist",
    "Photographer",
    "Petroleum Engineer",
    "Quantum Physicist",
    "Quality Assurance Analyst",
    "Quantity Surveyor",
    "Radiologist",
    "Real Estate Agent",
    "Robotics Engineer",
    "Social Worker",
    "Software Developer",
    "Statistician",
    "Technical Writer",
    "Teacher",
    "Tour Guide",
    "Urban Planner",
    "UX Designer",
    "Underwriter",
    "Veterinarian",
    "Video Game Developer",
    "Virtual Assistant",
    "Web Developer",
    "Wedding Planner",
    "Wildlife Biologist",
    "X-ray Technologist",
    "Xenobiologist",
    "Xerographer",
    "Yield Engineer",
    "Yoga Instructor",
    "Youth Counselor",
    "Zamboni Operator",
    "Zither Maker",
    "Zoologist"
  ]

//   function searchCareers () {
//     let searchCriteria = prompt("what career do you want to do")
//     console.log(searchCriteria)
//   }

//   searchCareers()

for (item in careers) {
    console.log(careers[item])
}